code/front-end/quemSomos/config/routes.rb
Rails.application.routes.draw do
  resources :phones
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

code/front-end/quemSomos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

code/front-end/quemSomos/app/models/person.rb
class Person < ApplicationRecord
    has_many :phones

    accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

    validates :nome, presence: true
    validates :email, presence: true, uniqueness: { case_sensitive: true }, format: { with: URI::MailTo::EMAIL_REGEXP }
    
end

code/front-end/quemSomos/app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person

  validates :numero, presence: true, numericality: { only_integer: false }, length: { minimum: 9, maximum: 9 }
end

code/front-end/quemSomos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

code/front-end/quemSomos/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_path, status: :see_other, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:nome, :email, phones_attributes: [:id, :numero, :_destroy])
    end
end

code/front-end/quemSomos/app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @phone.destroy!

    respond_to do |format|
      format.html { redirect_to phones_path, status: :see_other, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.require(:phone).permit(:numero, :person_id)
    end
end

code/front-end/quemSomos/app/helpers/application_helper.rb
module ApplicationHelper
end

code/front-end/quemSomos/app/helpers/people_helper.rb
module PeopleHelper
end

code/front-end/quemSomos/app/helpers/phones_helper.rb
module PhonesHelper
end

code/front-end/quemSomos/app/helpers/sobre_helper.rb
module SobreHelper
end

code/front-end/quemSomos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quem Somos" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag 'styles', media: 'all', data: { turbolinks: false } %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

code/front-end/quemSomos/app/views/people/_form.html.erb
<%= form_with(model: person, data: {controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper'}, html: { class: 'formulario' })  do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <template data-nested-form-target='template'>
      <%= form.fields_for :phones, Phone.new, child_index: 'NEW_RECORD' do |phone_fields| %>
        <%= render 'phone_form', f: phone_fields %>
      <% end %>
  </template>
  
  <%= form.fields_for :phones do |phone_fields| %>
    <%= render 'phone_form', f: phone_fields %>
    <br/>
  <% end %>
  
  <div data-nested-form-target="target"> </div>
  <br/>

  <button type = "button" data-action="nested-form#add">+ Celular </button>


  <div>
  <br/>
    <%= form.submit %>
  </div>
<% end %>

code/front-end/quemSomos/app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Nome:</strong>
    <%= person.nome %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

</div>

code/front-end/quemSomos/app/views/people/_phone_form.html.erb
<div class='nested-form-wrapper' data-new-record="<%= f.object.new_record? %>">
    <%= f.label :numero %>
    <%= f.text_field :numero %>
    <button type="button" data-action="nested-form#remove"> Remover Celular</button>

    <%= f.hidden_field :_destroy %>
</div>

code/front-end/quemSomos/app/views/people/edit.html.erb
<% content_for :title, "Editing person" %>

<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

code/front-end/quemSomos/app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "People" %>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

code/front-end/quemSomos/app/views/people/new.html.erb
<div class="container">   
    <div class="sidebar">
    </div>
    
    <div>
        <div class="content">
            <div class="quemsomos">
                <div>
                    <h1><b>Quem somos</b></h1>
                    <p>Somos uma plataforma inovadora dedicada a simplificar o processo de
                        compra de ativos, oferecendo aos investidores uma maneira eficiente
                        e acessível de adquirir bens tangíveis e intangíveis. Utilizamos
                        tecnologia avançada para integrar dados de mercado em tempo real,
                        por meio da API Alpha Vantage, proporcionando informações precisas
                        e atualizadas sobre os ativos.</p>
                </div>
                <%= image_tag 'qsomos1.jpeg', alt: 'Background image' %>
            </div>
    
            <div class="nossamissao">
                <div>
                    <h1><b>Nossa missão</b></h1>
                    <p>Nosso foco é oferecer uma experiência segura e confiável, terceirizando a
                        gestão financeira para o Mercado Pago, uma solução já consolidada no
                        mercado, para que possamos concentrar nossos esforços no que realmente
                        importa: facilitar a tomada de decisões dos nossos investidores.</p>
                </div>
                 <%= image_tag 'qsomos2.jpeg', alt: 'Background image' %>
            </div>
    
            <div class="duvidas">
                <h2><b>Ficou com dúvidas?</b></h2>
                <p>Quer saber mais sobre Ágora Kosmos? Preencha o formulário<br>com seus dados e um
                    dos nossos representantes entrará<br>em contato.
                </p>
            </div>
            <%= render "form", person: @person %>
            <div class="formulario">
              
              <h1><b>Formulário</b></h1>
              <label for="phone">Telefones para contato:</label>
              
              <div class="phone-input-container">
                  <input type="text" id="phone" name="phone">
                  <button type="button" class="add-phone">+</button>
              </div>
            </div>
        </div>
    </div>
</div>

code/front-end/quemSomos/app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

code/front-end/quemSomos/app/views/phones/_form.html.erb
<%= form_with(model: phone) do |form| %>
  <% if phone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
        <% phone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :person_id, style: "display: block" %>
    <%= form.text_field :person_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

code/front-end/quemSomos/app/views/phones/_phone.html.erb
<div id="<%= dom_id phone %>">
  <p>
    <strong>Numero:</strong>
    <%= phone.numero %>
  </p>

  <p>
    <strong>Person:</strong>
    <%= phone.person_id %>
  </p>

</div>

code/front-end/quemSomos/app/views/phones/edit.html.erb
<% content_for :title, "Editing phone" %>

<h1>Editing phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Show this phone", @phone %> |
  <%= link_to "Back to phones", phones_path %>
</div>

code/front-end/quemSomos/app/views/phones/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Phones" %>

<h1>Phones</h1>

<div id="phones">
  <% @phones.each do |phone| %>
    <%= render phone %>
    <p>
      <%= link_to "Show this phone", phone %>
    </p>
  <% end %>
</div>

<%= link_to "New phone", new_phone_path %>

code/front-end/quemSomos/app/views/phones/new.html.erb
<% content_for :title, "New phone" %>

<h1>New phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Back to phones", phones_path %>
</div>

code/front-end/quemSomos/app/views/phones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phone %>

<div>
  <%= link_to "Edit this phone", edit_phone_path(@phone) %> |
  <%= link_to "Back to phones", phones_path %>

  <%= button_to "Destroy this phone", @phone, method: :delete %>
</div>